import type { UserRole } from "@/types";
export type DemoCapability="VIEW_OWN_OUTLET"|"VIEW_PROVIDER_OPERATIONS"|"VIEW_ALERT_EVIDENCE"|"TRIAGE_ALERT"|"ASSIGN_CASE"|"ACKNOWLEDGE_CASE"|"ADD_CASE_NOTE"|"ESCALATE_CASE"|"REVIEW_UNUSUAL_ACTIVITY"|"COMPLETE_RISK_REVIEW"|"RESOLVE_OPERATIONAL_CASE"|"VIEW_DATA_HEALTH"|"RUN_SCENARIO"|"VIEW_METRICS"|"VIEW_AUDIT_LOG";
const shared:DemoCapability[]=["VIEW_ALERT_EVIDENCE"];
export const roleCapabilities:Record<UserRole,DemoCapability[]>={
 AGENT:[...shared,"VIEW_OWN_OUTLET","ADD_CASE_NOTE"],
 PROVIDER_OPERATIONS:[...shared,"VIEW_PROVIDER_OPERATIONS","TRIAGE_ALERT","ASSIGN_CASE","ACKNOWLEDGE_CASE","ADD_CASE_NOTE","ESCALATE_CASE","RESOLVE_OPERATIONAL_CASE","VIEW_DATA_HEALTH"],
 FIELD_OFFICER:[...shared,"VIEW_OWN_OUTLET","ACKNOWLEDGE_CASE","ADD_CASE_NOTE","ESCALATE_CASE"],
 RISK_ANALYST:[...shared,"REVIEW_UNUSUAL_ACTIVITY","ADD_CASE_NOTE","ESCALATE_CASE","COMPLETE_RISK_REVIEW","VIEW_AUDIT_LOG"],
 AREA_MANAGER:[...shared,"VIEW_PROVIDER_OPERATIONS","ASSIGN_CASE","ESCALATE_CASE","RESOLVE_OPERATIONAL_CASE","VIEW_METRICS","VIEW_AUDIT_LOG"],
 MANAGEMENT_VIEWER:[...shared,"VIEW_METRICS","VIEW_AUDIT_LOG"],
 SYSTEM_ADMIN:[...shared,"VIEW_DATA_HEALTH","RUN_SCENARIO","VIEW_METRICS","VIEW_AUDIT_LOG"],
};
export const hasDemoCapability=(role:UserRole,capability:DemoCapability)=>roleCapabilities[role].includes(capability);
