"""baseline schema

Revision ID: f7979cbb459d
Revises:
Create Date: 2026-07-11 20:59:16.968107
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types

revision: str = "f7979cbb459d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "areas",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "audit_event_records",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=32), nullable=True),
        sa.Column("actor_role", sa.String(length=32), nullable=True),
        sa.Column("case_id", sa.String(length=32), nullable=True),
        sa.Column("alert_id", sa.String(length=32), nullable=True),
        sa.Column("analysis_id", sa.String(length=32), nullable=True),
        sa.Column("before_status", sa.String(length=32), nullable=True),
        sa.Column("after_status", sa.String(length=32), nullable=True),
        sa.Column("case_version", sa.Integer(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", app.db.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_event_records_action"),
        "audit_event_records",
        ["action"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_event_records_case_id"),
        "audit_event_records",
        ["case_id"],
        unique=False,
    )
    op.create_table(
        "evaluation_metric_snapshots",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("metric_group", sa.String(length=32), nullable=False),
        sa.Column("evaluator_version", sa.String(length=64), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column(
            "measured_at", app.db.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evaluation_metric_snapshots_measured_at"),
        "evaluation_metric_snapshots",
        ["measured_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evaluation_metric_snapshots_metric_group"),
        "evaluation_metric_snapshots",
        ["metric_group"],
        unique=False,
    )
    op.create_table(
        "policy_snippets",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("alert_type", sa.String(length=64), nullable=False),
        sa.Column("permitted_action_categories", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scenarios",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "generated_at", app.db.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("is_synthetic_data", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "similar_case_summaries",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "synthetic_users",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("display_label", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("provider_scopes", sa.JSON(), nullable=False),
        sa.Column("area_scopes", sa.JSON(), nullable=False),
        sa.Column("agent_scopes", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agents",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("display_label", sa.String(length=128), nullable=False),
        sa.Column("area_id", sa.String(length=32), nullable=False),
        sa.Column("shared_cash_minor", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agents_area_id"), "agents", ["area_id"], unique=False)
    op.create_table(
        "analysis_records",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("scenario_id", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("pipeline_version", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=128), nullable=False),
        sa.Column("advisory_status", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at", app.db.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "completed_at", app.db.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("response_json", sa.JSON(), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("ai_latency_ms", sa.Integer(), nullable=True),
        sa.Column("error_category", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "agent_id", "idempotency_key", name="uq_analysis_agent_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_analysis_records_agent_id"),
        "analysis_records",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_records_scenario_id"),
        "analysis_records",
        ["scenario_id"],
        unique=False,
    )
    op.create_table(
        "provider_balances",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_balance_minor", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at", app.db.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "provider", name="uq_agent_provider"),
    )
    op.create_index(
        op.f("ix_provider_balances_agent_id"),
        "provider_balances",
        ["agent_id"],
        unique=False,
    )
    op.create_table(
        "provider_feed_states",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "last_received_at", app.db.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "checked_at", app.db.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("latency_seconds", sa.Integer(), nullable=False),
        sa.Column("feed_reported_balance_minor", sa.Integer(), nullable=False),
        sa.Column("ledger_balance_minor", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "provider", name="uq_agent_feed_provider"),
    )
    op.create_index(
        op.f("ix_provider_feed_states_agent_id"),
        "provider_feed_states",
        ["agent_id"],
        unique=False,
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("transaction_type", sa.String(length=32), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("synthetic_account_reference", sa.String(length=32), nullable=False),
        sa.Column(
            "occurred_at", app.db.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("repeated_amount", sa.Boolean(), nullable=False),
        sa.Column("velocity_flag", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_agent_id"), "transactions", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_occurred_at"),
        "transactions",
        ["occurred_at"],
        unique=False,
    )
    op.create_table(
        "alert_records",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("scenario_id", sa.String(length=64), nullable=False),
        sa.Column("analysis_id", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("alert_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at", app.db.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", app.db.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("snapshot_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analysis_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alert_records_agent_id"), "alert_records", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_alert_records_analysis_id"),
        "alert_records",
        ["analysis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alert_records_scenario_id"),
        "alert_records",
        ["scenario_id"],
        unique=False,
    )
    op.create_table(
        "case_records",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("alert_id", sa.String(length=32), nullable=False),
        sa.Column("analysis_id", sa.String(length=32), nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("area_id", sa.String(length=32), nullable=False),
        sa.Column("scope_type", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("required_role", sa.String(length=32), nullable=False),
        sa.Column("allowed_actions", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("assigned_to", sa.String(length=32), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", app.db.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", app.db.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "acknowledged_at", app.db.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "resolved_at", app.db.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("resolution_category", sa.String(length=64), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("dismissal_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(scope_type = 'PROVIDER' AND provider IS NOT NULL) OR "
            "(scope_type = 'AGENT' AND provider IS NULL)",
            name="ck_case_scope_provider",
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alert_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analysis_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["synthetic_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_case_records_agent_id"), "case_records", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_case_records_alert_id"), "case_records", ["alert_id"], unique=True
    )
    op.create_index(
        op.f("ix_case_records_analysis_id"),
        "case_records",
        ["analysis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_case_records_area_id"), "case_records", ["area_id"], unique=False
    )
    op.create_index(
        op.f("ix_case_records_assigned_to"),
        "case_records",
        ["assigned_to"],
        unique=False,
    )
    op.create_table(
        "case_note_records",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("case_id", sa.String(length=32), nullable=False),
        sa.Column("author_id", sa.String(length=32), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at", app.db.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["synthetic_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_case_note_records_case_id"),
        "case_note_records",
        ["case_id"],
        unique=False,
    )
    op.create_table(
        "human_decision_records",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("case_id", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=32), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("modified_actions", sa.JSON(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("case_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", app.db.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["synthetic_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "case_id", "fingerprint", name="uq_case_decision_fingerprint"
        ),
    )
    op.create_index(
        op.f("ix_human_decision_records_case_id"),
        "human_decision_records",
        ["case_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_human_decision_records_case_id"), table_name="human_decision_records"
    )
    op.drop_table("human_decision_records")
    op.drop_index(op.f("ix_case_note_records_case_id"), table_name="case_note_records")
    op.drop_table("case_note_records")
    op.drop_index(op.f("ix_case_records_assigned_to"), table_name="case_records")
    op.drop_index(op.f("ix_case_records_area_id"), table_name="case_records")
    op.drop_index(op.f("ix_case_records_analysis_id"), table_name="case_records")
    op.drop_index(op.f("ix_case_records_alert_id"), table_name="case_records")
    op.drop_index(op.f("ix_case_records_agent_id"), table_name="case_records")
    op.drop_table("case_records")
    op.drop_index(op.f("ix_alert_records_scenario_id"), table_name="alert_records")
    op.drop_index(op.f("ix_alert_records_analysis_id"), table_name="alert_records")
    op.drop_index(op.f("ix_alert_records_agent_id"), table_name="alert_records")
    op.drop_table("alert_records")
    op.drop_index(op.f("ix_transactions_occurred_at"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_agent_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(
        op.f("ix_provider_feed_states_agent_id"), table_name="provider_feed_states"
    )
    op.drop_table("provider_feed_states")
    op.drop_index(op.f("ix_provider_balances_agent_id"), table_name="provider_balances")
    op.drop_table("provider_balances")
    op.drop_index(
        op.f("ix_analysis_records_scenario_id"), table_name="analysis_records"
    )
    op.drop_index(op.f("ix_analysis_records_agent_id"), table_name="analysis_records")
    op.drop_table("analysis_records")
    op.drop_index(op.f("ix_agents_area_id"), table_name="agents")
    op.drop_table("agents")
    op.drop_table("synthetic_users")
    op.drop_table("similar_case_summaries")
    op.drop_table("scenarios")
    op.drop_table("policy_snippets")
    op.drop_index(
        op.f("ix_evaluation_metric_snapshots_metric_group"),
        table_name="evaluation_metric_snapshots",
    )
    op.drop_index(
        op.f("ix_evaluation_metric_snapshots_measured_at"),
        table_name="evaluation_metric_snapshots",
    )
    op.drop_table("evaluation_metric_snapshots")
    op.drop_index(
        op.f("ix_audit_event_records_case_id"), table_name="audit_event_records"
    )
    op.drop_index(
        op.f("ix_audit_event_records_action"), table_name="audit_event_records"
    )
    op.drop_table("audit_event_records")
    op.drop_table("areas")
    # ### end Alembic commands ###
